crop_thresh: 0.5
visual: True
warmup_frame: 50

DET:
  model_dir: ./model/mot_ppyoloe_l_36e_ppvehicle
  batch_size: 1

MOT:
  model_dir: ./model/mot_ppyoloe_l_36e_ppvehicle
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: -1 # preferably no more than 3
  enable: True

VEHICLE_PLATE:
  det_model_dir: ./model/Multilingual_PP-OCRv3_det_infer
  det_limit_side_len: 736
  det_limit_type: "min"
  rec_model_dir: ./model/japan_PP-OCRv3_rec_infer
  rec_image_shape: [3, 48, 320]
  rec_batch_num: 6
  word_dict_path: deploy/pipeline/ppvehicle/japan_dict.txt
  enable: False

VEHICLE_ATTR:
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/vehicle_attribute_model.zip
  batch_size: 8
  color_threshold: 0.5
  type_threshold: 0.5
  enable: False

LANE_SEG:
  lane_seg_config: deploy/pipeline/config/lane_seg_config.yml
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/pp_lite_stdc2_bdd100k.zip

VEHICLE_PRESSING:
  enable: False

VEHICLE_RETROGRADE:
  frame_len: 8
  sample_freq: 7
  enable: False
  filter_horizontal_flag: True
  keep_right_flag: True
  deviation: 23
  move_scale: 0.01
  fence_line: [] #[x1,y1,x2,y2] y2>y1.
